version: '3'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${BD_USERNAME}
      POSTGRES_PASSWORD: ${BD_PASSWORD}
      POSTGRES_DB: ${BD_DATABASE}
    ports:
      - "${BD_PORT}:${BD_PORT}"
  api:
    build: .
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      PGUSER: ${BD_USERNAME}
      PGHOST: ${BD_HOST}
      PGDATABASE: ${BD_DATABASE}
      PGPASSWORD: ${BD_PASSWORD}
      PGPORT: "${BD_PORT}"

